wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.7
    start_time: 1667259352.7486
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 13
      - 14
      - 16
      - 23
      4: 3.10.7
      5: 0.13.4
      8:
      - 5
created_at:
  desc: null
  value: '2022-05-15T14:05:21'
fine_tuned_model:
  desc: null
  value: curie:ft-personal-2022-05-15-21-36-28
hyperparams:
  desc: null
  value:
    batch_size: 4
    learning_rate_multiplier: 0.1
    n_epochs: 4
    prompt_loss_weight: 0.1
id:
  desc: null
  value: ft-ExLKmX3cZFk3X6f8QvvIPSXZ
model:
  desc: null
  value: curie
n_train:
  desc: null
  value: 2500
object:
  desc: null
  value: fine-tune
organization_id:
  desc: null
  value: org-TYqZWSDRo9AkLmlNmJh6F5x0
result_files:
  desc: null
  value:
    bytes: 145852
    created_at: 1652650590
    filename: compiled_results.csv
    id: file-6zng21IqCAwFydif54pJxIoO
    object: file
    purpose: fine-tune-results
    status: processed
    status_details: null
status:
  desc: null
  value: succeeded
training_files:
  desc: null
  value:
    bytes: 987086
    created_at: 1652648720
    filename: jsonl/records-nameonly.jsonl
    id: file-xmyAt3iVR2Qq6aoALuKvGfb3
    object: file
    purpose: fine-tune
    status: processed
    status_details: null
updated_at:
  desc: null
  value: 1652650593
validation_files:
  desc: null
  value: []
