wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.7
    start_time: 1667259370.845373
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 13
      - 14
      - 16
      - 23
      4: 3.10.7
      5: 0.13.4
      8:
      - 5
created_at:
  desc: null
  value: '2022-05-20T16:07:33'
fine_tuned_model:
  desc: null
  value: curie:ft-personal-2022-05-20-23-11-58
hyperparams:
  desc: null
  value:
    batch_size: 1
    learning_rate_multiplier: 0.1
    n_epochs: 4
    prompt_loss_weight: 0.1
id:
  desc: null
  value: ft-MGDDsmwddSoAY9QByptpIB2i
model:
  desc: null
  value: curie
n_train:
  desc: null
  value: 200
object:
  desc: null
  value: fine-tune
organization_id:
  desc: null
  value: org-TYqZWSDRo9AkLmlNmJh6F5x0
result_files:
  desc: null
  value:
    bytes: 32922
    created_at: 1653088320
    filename: compiled_results.csv
    id: file-IL03b48R3UzPHxiUbvcpIvqp
    object: file
    purpose: fine-tune-results
    status: processed
    status_details: null
status:
  desc: null
  value: succeeded
training_files:
  desc: null
  value:
    bytes: 12899
    created_at: 1653088052
    filename: playcalls.jsonl
    id: file-6OuLyjVsFNaa6Sv1wYWNpvCJ
    object: file
    purpose: fine-tune
    status: processed
    status_details: null
updated_at:
  desc: null
  value: 1653088323
validation_files:
  desc: null
  value: []
